language: python
os: linux
dist: xenial
sudo: true

matrix:
    include:
        - python: 3.7
        #   dist: xenial
        #   sudo: true

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y imagemagick; fi

install:
    - pip install -r requirements.txt
    - pip install flake8 pylint

script:
    - flake8 pywalc setup.py
    - pylint pywalc setup.py
